services:
  redis:
    image: redis:8.8-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ticket-network

  ticket-api:
    container_name: ticket-api
    build:
      context: .
    depends_on:
      - redis
    networks:
      - ticket-network
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

networks:
  ticket-network:
    name: ticket-network
    external: true
